### ISSUE TITLE
Dead domains in Blacklist_DNS

### ISSUE THREAD

**Issue by smed79** [nightznero/NIGHTZNERO-Filter-Lists#2]
Blacklist_DNS (version 2024.02.20) has 1116 INACTIVE domains.

[dead-domains.txt](https://github.com/nightznero/NIGHTZNERO-Filter-Lists/files/14364625/dead-domains.txt)

**Comment by nightznero** [comment]
> Blacklist_DNS (version 2024.02.20) has 1116 INACTIVE domains.
> 
> [dead-domains.txt](https://github.com/nightznero/NIGHTZNERO-Filter-Lists/files/14364625/dead-domains.txt)

Helloz,
Well,i looked into file and can say;
There are only very few "dead" sites,but i added em manually and especially. Like for e.x about `FitGirl Repacks` or `ExpressVPN` True they are dead but I added them cuz they are abused for malvetising. Personally I or anyone who would like to use this list will be not directed to fake site cuz they are blocked.

Here's a lot of windows domains,I don't use a windows in a while so hard foe me to check that but they are come from `MAX Spy-block` list and belive it's must ping inside some windows apps.

There are also domains like `shepherd.ff.avast.com.piriform.com`
`googleads.github.io`
`pagead.googlesyndication.com`
`cdn.ad.xiaomi.com`
Site like this are not dead, Shepherd domain is pinged in Avast One,pagead is pinged in YouTube/YouTube Music.

Thanks for reporting but most of them cannot be deleted

**Comment by smed79** [comment]
I understand perfectly :+1:
